on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - release/*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  my_job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    name: deploy to staging
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          #pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
